# Welcome to My Site!
# This is an attempt to learn github and getting familiar with jekyll
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nithin Rajan
email: nitinraj90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a test site to learn github and jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: davidnithinrajan
facebook_username: davidnitinrajan
github_username:  NithinRajan

# Build settings
markdown: kramdown
